title: PACE Data Hackweek
author: OCB (content), UW/eScience Institute (template)
logo: img/PACE-water-design-High-res.png
only_build_toc_files: false
parse:
  myst_substitutions:
    hackweek: "PACE Data Hackweek"
    dates: "August 3 to 7, 2025"
    github_org_url: "https://github.com/PACEHackWeek"
    book_repo: "pace-2025"
    website_url: "https://pacehackweek.github.io/pace-2025"
    jupyterhub_url: <a href="https://hub.cryointhecloud.com" target="_blank">https://hub.cryointhecloud.com</a>
    slack_workspace_url: <a href="https://cryospherecloud.slack.com/archives/C075ASE8Z8W" target="_blank">https://cryospherecloud.slack.com</a>
    contact_email: "anna.windledipaola@nasa.gov"
    anon_reporting_url: "https://www.us-ocb.org/about/ocb-program-code-of-conduct"
    project_spreadsheets_url: <a href="https://docs.google.com/spreadsheets/d/1vMjwZMHkr4zlRKyN8WcwCwMBhtX6HHZU9Nn7UZDevY4" target="_blank">Group Projects</a>
    l0: "{fas}`eye;sd-text-light`"
    l1: "{fas}`eye;sd-text-primary`"
    d0: "{fas}`download;sd-text-light`"
    d1: "{fas}`download;sd-text-primary`"
    v0: "{fab}`youtube;sd-text-light`"
    v1: "{fab}`youtube;sd-text-primary`"
  myst_enable_extensions:
    # defaults
    - dollarmath
    - linkify
    - substitution
    - colon_fence
    # extras
    - html_image
  myst_url_schemes:
    - http
    - https
    - mailto
    - ftp
execute:
  execute_notebooks: off
latex:
  latex_documents:
    targetname: book.tex
repository:
  url: "https://github.com/PACEHackWeek/pace-2025"
  path_to_book: book
  branch: main
bibtex_bibfiles:
  - references.bib
sphinx:
  config:
    bibtex_reference_style: author_year
    nb_merge_streams: true
    nb_custom_formats:
      .ipynb:
        - nbformat.reads
        - as_version: 4
        - false # setting to the default `true` seems to break math, `false` uses MyST instead of Commmonmark
html:
  # announcement: "Content under development, check back for updates!"
  use_edit_page_button: true
  use_issues_button: true
  use_repository_button: true
  favicon: "https://web.whoi.edu/ocb/wp-content/uploads/sites/43/builder-favicon/4dYqnNNS.ico"
