# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: PACE Data Hackweek
author: OCB (content), UW/eScience Institute (template)
logo: img/PACE-water-design-High-res.png
only_build_toc_files: true

parse:
  # https://jupyterbook.org/content/content-blocks.html?highlight=myst%20substitution#define-substitutions-for-your-whole-book
  # https://jupyterbook.org/content/content-blocks.html#using-substitutions-in-links
  myst_substitutions:
    hackweek: "PACE Data Hackweek"
    dates: "August 3 to 7, 2025"
    github_org_url: "https://github.com/PACEHackWeek"
    book_repo: "pace-2025"
    website_url: "https://PACEHackWeek.github.io/pace-2025"
    jupyterhub_url: <a href="https://hub.cryointhecloud.com" target="_blank">https://hub.cryointhecloud.com</a>
    slack_workspace_url: <a href="https://cryospherecloud.slack.com/archives/C075ASE8Z8W" target="_blank">https://cryospherecloud.slack.com</a>
    contact_email: "anna.windledipaola@nasa.gov"
    anon_reporting_url: "https://www.us-ocb.org/about/ocb-program-code-of-conduct"
    project_spreadsheets_url: <a href="https://docs.google.com/spreadsheets/d/1vMjwZMHkr4zlRKyN8WcwCwMBhtX6HHZU9Nn7UZDevY4" target="_blank">Group Projects</a>
    l0: "{fas}`eye;sd-text-light`"
    l1: "{fas}`eye;sd-text-primary`"
    d0: "{fas}`download;sd-text-light`"
    d1: "{fas}`download;sd-text-primary`"
    v0: "{fab}`youtube;sd-text-light`"
    v1: "{fab}`youtube;sd-text-primary`"
  myst_enable_extensions:
    # Defaults
    - dollarmath
    - linkify
    - substitution
    - colon_fence
    # Extras
    - html_image

# See https://jupyterbook.org/content/execute.html
execute:
  # NOTE: 'cache' to use jupyter-cache, or 'force' to run all
  execute_notebooks: off
  exclude_patterns:
    - "**/*.ipynb"
  allow_errors: true
  # Per-cell notebook execution limit (seconds)
  timeout: 300

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: "https://github.com/PACEHackWeek/pace-2025" # Online location of your book
  path_to_book: book  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Bibliography
bibtex_bibfiles:
  - references.bib
sphinx:
  config:
    bibtex_reference_style: author_year  # or label, super, \supercite
    nb_merge_streams: true # stdout lines combined in output
    nb_custom_formats:
      .ipynb:
        - nbformat.reads
        - as_version: 4
        - false # setting to `true` breaks math for some reason, `false` uses MyST instead of Commmonmark

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  announcement: "Content under development, check back for updates!"
  use_edit_page_button: true
  use_issues_button: true
  use_repository_button: true
  favicon: "https://web.whoi.edu/ocb/wp-content/uploads/sites/43/builder-favicon/4dYqnNNS.ico"
  # google_analytics_id: G-XXXXXXXXX
